server:
  servlet:
    context-path: /profile
  port: 8078

spring:
  application:
    name: profile

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://profile-api-service-db:5432/capstoneprojectsdb
    username: postgres
    password: password
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    properties.hibernate.format_sql: true

springdoc:
  api-docs:
    path: '/api-docs'

eureka:
  instance:
    instance-id: ${spring.application.name}



