server:
  servlet:
    context-path: /profiles
  port: 8077

spring:
  application:
    name: profiles

  profiles:
    active: dev

springdoc:
  api-docs:
    path: '/api-docs'

eureka:
  instance:
    instance-id: ${spring.application.name}



